import { START, StateGraph, StateSchema, type GraphNode, END, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod"
import { mistralAIModel, cohereAIModel, geminiAIModel } from "./model.ai.js"
import { createAgent, HumanMessage, providerStrategy } from "langchain"
import { BaseMessage } from "@langchain/core/messages";


const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default("")
    })

})

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereAIModel.invoke(state.problem)
    ])

    const mResponse = mistralResponse as unknown as BaseMessage
    const cResponse = cohereResponse as unknown as BaseMessage

    return {
        solution_1: mResponse.content?.toString() || "",
        solution_2: cResponse.content?.toString() || ""
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judgeModel = createAgent({
        model: geminiAIModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string()
        })),
        systemPrompt: `You are a judge tasked with evaluating two AI solutions generated by diffent AI models to the problem : ${problem}. Please provide a scoe out of 10 for each solution, along with your reasing for the scores`,

    })

    const judgeResponse = await judgeModel.invoke({
        messages: [
            new HumanMessage(`
                    Problem: ${problem}
                    solution_1: ${solution_1}
                    solution_2: ${solution_2}
                    Please evaluate the solutions and provide scores and reasoning for each solution.
                `)
        ]
    })


    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solutionNode", solutionNode)
    .addNode("judgeNode", judgeNode)
    .addEdge(START, "solutionNode")
    .addEdge("solutionNode", "judgeNode")
    .addEdge("judgeNode", END)
    .compile()

export default async function runGraph(problem: string) {
    const result = await (graph as any).invoke({
        problem: problem
    })

    return result
}