/**
 * AI stream service for streaming AI responses to the client.
 *
 * Uses LangChain's model.stream() to stream tokens and sends each chunk to the client via the onChunk callback.
 */

import { AIMessage, HumanMessage, SystemMessage } from "langchain";

import { agent } from "./ai.service.js";

/**
 * Streams AI responses chunk by chunk to the client
 * @param {Object[]} messages - Array of messages
 * @param {string} systemPrompt - System prompt
 * @param {function} onChunk - Callback to send each chunk to the client
 * @returns {Promise<string>} - Full response from AI
 */
export async function streamResponse({
  messages,
  systemPrompt,
  onChunk,
  signal,
  onSources,
}) {
  const formattedMessages = messages
    .map((msg) => {
      if (msg.role === "user") {
        return new HumanMessage(msg.content);
      }

      if (msg.role === "ai") {
        return new AIMessage(msg.content);
      }

      return null;
    })
    .filter(Boolean);

  // Use streamEvents to capture both token streams and tool execution events
  // Pass the abort signal directly to the LangChain streamEvents execution options.
  const eventStream = await agent.streamEvents(
    { messages: [new SystemMessage(systemPrompt), ...formattedMessages] },
    { version: "v2", signal },
  );

  let fullResponse = "";
  let sources = [];

  for await (const event of eventStream) {
    // 1. Capture text tokens generated by the Mistral Chat Model
    if (event.event === "on_chat_model_stream") {
      const content = event.data.chunk?.content;
      if (content) {
        fullResponse += content;
        onChunk(content);
      }
    }

    // 2. Capture search tool output when the search tool ends
    if (event.event === "on_tool_end" && event.name === "searchInternet") {
      try {
        const toolOutput = event.data.output;
        if (toolOutput && toolOutput.content) {
          const searchData = JSON.parse(toolOutput.content);

          if (searchData && searchData.results) {
            sources = searchData.results.map((result) => ({
              title: result.title,
              url: result.url,
            }));
            if (onSources) {
              onSources(sources);
            }
          }
        }
      } catch (err) {
        console.error("Error parsing search tool sources in stream: ", err);
      }
    }
  }

  return {
    content: fullResponse,
    sources,
  };
}
